### ISSUE TITLE
Where can I download the system image specified in kernelinfo.conf?

### ISSUE THREAD

**Issue by davidyoung8906** [moyix/panda#100]
Hi!
     I get errors of unable to read kernel info when running the file taint plugin even after porting my system conf to the kernelinfo.conf file. I plan to switch to system specified in the kernelinfo.conf. Can you point me to where can I download these system images? For example, where can I download the "lava32" image: name = #1 SMP Debian 3.2.51-1 i686?

Thanks!

**Comment by moyix** [comment]
It's difficult to share entire system images since they're many gigabytes large. It would be simpler for you to just create a kernelinfo configuration that matches your current system; there are instructions here:

https://github.com/moyix/panda/blob/master/qemu/panda_plugins/osi_linux/USAGE.md

**Comment by davidyoung8906** [comment]
Yes. I tried to follow the instruction for Ubuntu but failed. Could you let
me know which Ubuntu version works best for the plugin?

**Comment by davidyoung8906** [comment]
Hi! Can anyone recommend an Ubuntu version or any well known system images?

**Comment by hijkrix** [comment]
You can download _debian-panda-qcow_ [here](https://people.debian.org/~aurel32/qemu/i386/debian_squeeze_i386_standard.qcow2)

**Comment by davidyoung8906** [comment]
Thanks for the image. However, I have problem to boot the system (See below
![no boot](https://cloud.githubusercontent.com/assets/1767219/15234113/d2ea2086-1873-11e6-9f5c-0b140c5f2902.png)
).

**Comment by moyix** [comment]
Are there any messages on the console?

The most likely issue is that you will probably need to convert the qcow to the older QEMU format. You can do that by using `qemu-img -O qcow2 -o compat=0.10 input.qcow2 output.qcow2`.

**Comment by moyix** [comment]
Closing for now. Let me know if this is still not working.
