### ISSUE TITLE
libdwarf: no such file or directory

### ISSUE THREAD

**Issue by Fiddlesteak** [moyix/panda#102]
So it seems like I'm already too dump for a simple build...
I'm trying to build panda on my kali linux and had several issues with installing, all in all I did a lot self-fixing with more or less working results and now when I try to build panda I get this message 3 times. If someone is interested in the complete log, I will add it.
What is libdwarf? I don't seem to find anything matching in the list of panda's prerequisites...

**Comment by RickyUlrich** [comment]
@Fiddlesteak : libdwarf is a dwarf producer consumer library that gives PANDA source code level knowledge during a replay.  
I updated the doc/compile.md if you're interested in how to install libdwarf.  If you just run panda_install.bash again, libdwarf will be installed as well.  If you prefer, you can continue with the panda build by commenting out any dwarf related plugins (dwart_taint, dwarf_simple, dwarfp) in your qemu/panda_plugins/config.panda file and then running qemu/build.sh
Hope this helps,
Ricky
