### ISSUE TITLE
qemu-system-x86_64: -replay: invalid option

### ISSUE THREAD

**Issue by Fiddlesteak** [moyix/panda#103]
Hey, having a dumb issue here, every time I try to replay a recording, I get this error (and it is the only feedback I get from qemu):
`qemu-system-x86_64: -replay: invalid option`
I built it properly with `build.sh` without any errors so I don't really get whats going on now huh

**Comment by phulin** [comment]
What's the full command line? You might be accidentally using the system
QEMU instead of the PANDA modified version.

On Sunday, May 29, 2016, Freenk <notifications@github.com> wrote:

> Hey, having a dumb issue here, every time I try to replay a recording, I
> get this error (and it is the only feedback I get from qemu):
> qemu-system-x86_64: -replay: invalid option
> I built it properly with build.sh without any errors so I don't really
> get whats going on now huh
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/moyix/panda/issues/103>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAhgh1R5qHpZd_7jXplRIHQP9Lbqalv1ks5qGZvggaJpZM4IpS7i>
> .
>


-- 
Sent using a stone tablet and chisel. Please excuse the brevity.

**Comment by Fiddlesteak** [comment]
Thanks for the fast replay,

the full command line is:
`me@stillme:~/Downloads/panda-master/qemu/x86_64-softmmu$ sudo qemu-system-x86_64 -m 1024 -replay '/home/me/spotify' -panda callstack_instr -panda unigrams
`

As you can see I'm trying to follow along moyix post on Push the Red Button to get to know PANDA

**Comment by phulin** [comment]
Yep, that's exactly the problem. You need to use "./qemu-system-x86_64",
not qemu-system-x86_64, which uses your system QEMU
(/usr/bin/qemu-system-x86_64).

**Comment by Fiddlesteak** [comment]
Uuhm, it could be possible that I am retarded as fuck but yes, now it works but where is the difference????
And yea, actually it doesn't work, I'm getting a new error now: after the loading and the initializing of the plugins, I get:

`loading snapshot
qemu-system-x86_64: Could not open VM state file
... done.
opening nondet log for read :	./spotify-rr-nondet.log
RR rr_assertion `rr_nondet_log->fp != NULL' failed at /home/frank/Downloads/panda-master/qemu/rr_log.c:1323
Current log point:
<queue empty>
Current replay point:
{guest_instr_count=0 pc=0x00000000, secondary=0x00000000}
`

Should I create a new issue for that or can you help me directly?
