### ISSUE TITLE
qemu-system-x86_64: Could not open VM state file

### ISSUE THREAD

**Issue by Fiddlesteak** [moyix/panda#104]
Hello, every time I try to replay the recording moyix used to show PANDA's abilities in his post on Push the Red Button, I get the following error message:

loading snapshot
qemu-system-x86_64: Could not open VM state file
... done.
opening nondet log for read : ./spotify-rr-nondet.log
RR rr_assertion `rr_nondet_log->fp != NULL' failed at /home/frank/Downloads/panda-master/qemu/rr_log.c:1323
Current log point:

Current replay point:
{guest_instr_count=0 pc=0x00000000, secondary=0x00000000}

don't really get what the problem is, would appreciate help!

**Comment by moyix** [comment]
It looks like you don't have the spotify recording unpacked. Did you do `rrunpack.py spotify.rr` and then use `-replay spotify` in the directory where you unpacked it?

**Comment by Fiddlesteak** [comment]
#103

**Comment by Fiddlesteak** [comment]
I did unpack it of cause ^^
Just to double-check, I unpacked it again, running rrunpack gave me this:

`me@stillme:~/Downloads/panda-master/scripts$ sudo python rrunpack.py
'/home/me/Downloads/spotify.rr'`
`Verifying checksum... Success.`
`spotify-rr-snp`
`spotify-rr-nondet.log`
`Unacking RR log /home/me/Downloads/spotify.rr with 12038235466 instructions... Done.`

Still the same... here is the full command line btw:

`me@stillme:~/Downloads/panda-master/qemu$ sudo x86_64-softmmu/qemu-system-x86_64 -m 1024 -replay '/home/me/Downloads/spotifyproject' -panda callstack_instr -panda unigrams`

**Comment by moyix** [comment]
`rrunpack.py` gives you `spotify-rr-snp` and `spotify-rr-nondet.log`. Say they're in `/home/me/Downloads/spotifyproject`. Then you want:

```
x86_64-softmmu/qemu-system-x86_64 -m 1024 -replay /home/me/Downloads/spotifyproject/spotify -panda callstack_instr -panda unigrams
```

**Comment by Fiddlesteak** [comment]
Oh thank you very much, I got that wrong, now it works, appreciate the amazing support
