### ISSUE TITLE
Install Panda on CentOS 7(glib2.0 required)

### ISSUE THREAD

**Issue by mudongliang** [moyix/panda#106]
When I tried to install panda on CentOS 7, I encountered error, the following is output : 

```
$ ./build.sh 
Building API for plugin sample ... Done!
Building API for plugin taint ... Done!
Building API for plugin taint2 ... Done!
Building API for plugin callstack_instr ... Done!
Building API for plugin bir ... Done!
Building API for plugin osi ... Done!
Building API for plugin osi_linux ... Done!
Building API for plugin pri ... Done!
Building API for plugin pri_dwarf ... Done!
Building API for plugin wintrospection ... Done!
panda_plugins/dead_data/dead_data.proto
panda_plugins/taint2/taint2.proto
panda_plugins/callstack_instr/callstack_instr.proto
panda_plugins/bir/bir.proto
panda_plugins/tainted_branch/tainted_branch.proto
panda_plugins/asidstory/asidstory.proto
panda_plugins/file_taint/file_taint.proto
panda_plugins/win7proc/win7proc.proto
panda_plugins/ida_taint2/ida_taint2.proto
panda_plugins/tainted_instr/tainted_instr.proto
panda_plugins/pri_dwarf/pri_dwarf.proto
panda_plugins/pri_taint/pri_taint.proto
generating protobuf code with protoc-c
No suitable LLVM found -- LLVM SUPPORT IS DISABLED
glib-2.0 required to compile QEMU
```
However, I have installed glib on my CentOS 7.
```
rpm -qa | grep glib
glibc-common-2.17-106.el7_2.6.x86_64
glibc-devel-2.17-106.el7_2.6.x86_64
glibc-2.17-106.el7_2.6.x86_64
dbus-glib-0.100-7.el7.x86_64
glib2-2.42.2-5.el7.x86_64
glib-networking-2.42.0-1.el7.x86_64
glibc-headers-2.17-106.el7_2.6.x86_64
```

And I use the following "yum" commands to replace apt-get commands.
```
sudo yum groupinstall 'Development Tools'
(http://unix.stackexchange.com/questions/16422/cant-install-build-essential-on-centos)

sudo yum install nasm openssl-devel libpcap-devel subversion curl autoconf libtool \
  python-pip git protobuf-compiler protobuf-c-compiler  protobuf-c-devel protobuf-devel \
  glibc-devel elfutils-libelf-devel
```

**Comment by moyix** [comment]
My guess is you're missing the development headers for glib. The package should be named something like `glib-2.0-devel`.

You may also want to try running `yum-builddep qemu`. `yum-builddep` should be part of the `yum-utils` package.

**Comment by mudongliang** [comment]
I have found it. Its name is glib2-devel. Thanks. And the panda is compiling without support of llvm. Which plugins needs the support of llvm?

**Comment by phulin** [comment]
It's needed for the taint tracking plugin and everything that depends on it.

On Wednesday, June 8, 2016, Dongliang Mu <notifications@github.com> wrote:

> I have found it. Its name is glib2-devel. Thanks. And the panda is
> compiling without support of llvm. Which plugins needs the support of llvm?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/moyix/panda/issues/106#issuecomment-224653341>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAhghxXOsLr8twt5_xO4xOh8yjg8yUcYks5qJvI3gaJpZM4IwWEt>
> .
>


-- 
Sent using a stone tablet and chisel. Please excuse the brevity.
