### ISSUE TITLE
pri_dwarf_types.h: No such file or directory (fatal error; compilation terminated)

### ISSUE THREAD

**Issue by tgduckworth** [moyix/panda#111]
Beginning with 0d8a8f30a534c739de34de7a15e200fe338b663c it appears that several files for the pri_dwarf panda plugin attempt to include a header (pri_dwarf_types.h) that has not been included with the project, causing compilation to fail.

**Comment by moyix** [comment]
Fixed by 367d013ca17c4a466023ceb18eeefb0fd82f5b03.
