### ISSUE TITLE
QEMU process quits after several hours

### ISSUE THREAD

**Issue by mnavaki** [moyix/panda#122]
QEMU process exits after several hours(like 10 hours or so). Even when I don't load any plugins or anything, still QEMU tend to quit after several hours. I don't know why? I don't know if this is related to the old version of QEMU that PANDA uses or what. Any thoughts? 

My host OS is Ubuntu 14.04 and my guest OS is Windows 7.

**Comment by moyix** [comment]
Could you say what you mean by "quits"? Does it crash? Run out of memory?

**Comment by mnavaki** [comment]
No, it does not sound like a crash. It just dies randomly, and no one kills the process.

**Comment by moyix** [comment]
Could you run it under gdb and get a backtrace when it exits?

**Comment by mnavaki** [comment]
I could not get it working under gdb. It was complaining that "no symbol table loaded". Is it necessary to enable QEMU/PANDA for debugging in build.sh in order to be able to run it under gdb? Because when I enable debugging in build.sh (under qemu directory) QEMU crashes at start-up with a "tcg fatal error".

**Comment by moyix** [comment]
Are you debugging the unstripped binary (i.e., the one found in `i386-softmmu/qemu-system-i386`? That should have debugging symbols enabled. If are running `make install` and then trying to use gdb on the binary int installs to the bin directory, that one will be stripped and isn't suitable for debugging.

I'm not sure why `--enable-debug` isn't working, but you should be able to just add `-O0 -g` to the `--extra-cflags` and `--extra-cxxflags` to achieve the same effect.

**Comment by mnavaki** [comment]
I instrumented a bunch of log messages in QEMU/PANDA source code, and realized that QEMU/PANDA receives a "qemu_system_shutdown_request" and then unload plugins and exits the main loop(in vl.c) and returns 0 at the end. The same routine when I execute "quit" command in the QEMU command prompt! Under what conditions PANDA/QEMU would act like this?

**Comment by moyix** [comment]
It shouldn't as far as I know. Could you set a breakpoint on `qemu_system_shutdown_request` and see who's calling it?

**Comment by mnavaki** [comment]
That's what I'm trying to do...

**Comment by moyix** [comment]
Also note that `qemu_system_shutdown_request` can also be called if the *guest* initiates the shutdown. So you may want to check if something in the guest is triggering system shutdown, e.g. Windows Update.

**Comment by mnavaki** [comment]
You were right. The problem was the guest OS. It was crashing because of BSoD and sending shutdown request to QEMU (instead of reset request)! I just replaced the image with a fresh Windows image, and the problem resolved.

**Comment by moyix** [comment]
Cool, I'll close this then.
