### ISSUE TITLE
Replay failure: Infinite loop detected during replay, aborting

### ISSUE THREAD

**Issue by yshalabi** [moyix/panda#16]
The instruction it is failing at is not very interesting, just a LEA x86 instruction. Pointers on where to read about debugging and inspecting replay log files will be helpful.

**Comment by moyix** [comment]
@yshalabi Not sure if you're still using PANDA, but if so, could you give it another try with the current version? We just found and fixed a problem where some Linux distros had VMWare mouse support turned on, which caused replay failures.

**Comment by yshalabi** [comment]
Unfortunately I lost track of this and I don't think I still have the
replay log that was causing this issue. Sorry.

**Comment by moyix** [comment]
No problem. I'll close this for now, let me know if it recurs!

**Comment by gitttt** [comment]
I got the same error.
I recorded like this:
1.) Starting the guest
/home/vagrant/panda/qemu/i386-softmmu/qemu-system-i386 -hda panda_disk.qcow -m 512 -monitor stdio
2.) begin_record test_record_ls
3.) "shutdown -h now" on the guest

I then tried to replay it like this:
/home/vagrant/panda/qemu/i386-softmmu/qemu-system-i386 -replay test_record_ls

which gave me:
```
loading snapshot
Block expected 134217728, found 536870912, total 545718272, system total 143065088
qemu: warning: error while loading state for instance 0x0 of device 'ram'
qemu-system-i386: Error -22 while loading VM state
... done.
opening nondet log for read :	./test_record_ls-rr-nondet.log
Infinite loop detected during replay, aborting.
{guest_instr_count=0 pc=0x0000fff0, secondary=0x00000000}
test_record_ls:           0 (  0.00%) instrs.    0.96 sec.  0.03 GB ram.
total_instr in replay:   19909329
ERROR: replay failed!
Time taken was: 0 seconds.
max_queue_len = 1
0 items on recycle list, 0 bytes total
ERROR: replay failed!
Aborted (core dumped)
```

My solution:
Starting the replay like this:
/home/vagrant/panda/qemu/i386-softmmu/qemu-system-i386 -replay test_record_ls -m 512 -monitor stdio
