### ISSUE TITLE
Make syscalls plugin use PPP instead of implementing VMI callbacks

### ISSUE THREAD

**Issue by jhodosh** [moyix/panda#17]
PANDA shouldn't have AFTER_FORK, AFTER_EXEC, or AFTER_CLONE callbacks.
Make them exported from the syscalls plugin using PPP.

Since the DroidScope Linux introspection code uses those callbacks, it must be ported to its own plugin.
The DroidScope code does invasive things like "get memory using PGD value" which switches out the PGD in env, does its memory access, and switches it back.

**Comment by phulin** [comment]
Closing since syscalls has been reinvented as syscalls2.
