### ISSUE TITLE
Replays fail if VMWare Tools is installed

### ISSUE THREAD

**Issue by moyix** [moyix/panda#18]
@rjwhelan noticed that if VMWare Tools is installed in the guest when a recording is taken, replays will fail. The point of failure is at `RR_CALLSITE_IOPORT_READ`, which leads me to suspect that it's caused by the [VMWare backdoor](https://sites.google.com/site/chitchatvmback/backdoor), but we should still be able to handle this case.

Until then, note that the workaround is to just uninstall the VMWare tools (they don't do anything in PANDA anyway).

**Comment by moyix** [comment]
Update: this is also causing replay failures in Debian 7 (wheezy) in the default setup. The culprit is the `xserver-xorg-input-vmmouse` package, which uses the VMWare backdoor to do mouse movements using a mechanism that isn't captured by record/replay (it writes directly to the CPU registers from a device). Workaround for now is to just remove that package.

**Comment by m000** [comment]
After the fix, will one be able to replay traces that were affected by the bug?

Or the fix means that if you re-capture an "equivalent" trace, it will now be replayable?

**Comment by phulin** [comment]
You'll have to rerecord, as the old traces will contain the guest agent
stuff which we don't handle properly. This is a workarouund and not a fix.

**Comment by m000** [comment]
Ok. Thanks. That was my understanding too.
