### ISSUE TITLE
Make PANDA changes to QEMU patchfiles instead of source

### ISSUE THREAD

**Issue by aoighost** [moyix/panda#32]
Moving the PANDA changes to QEMU to patchfiles would make it easier to update QEMU used by PANDA when needed, which will allow for more and better functionality in analysis.

Examples of new functionality that has been added to QEMU that isn't in PANDA includes things such as USB and PCI Passthrough support. Both of these things can be very useful when analyzing more advanced applications.

**Comment by phulin** [comment]
Closing since I don't think this is easily fixable. We have some long-term plans to update the version of qemu, but record/replay is very finicky and very strongly tied to qemu internals. For reference, upgrading RR from 0.9.4 to 1.0.1 was about a summer's worth of full-time work for one person.
