### ISSUE TITLE
some problems in runpandroid.py

### ISSUE THREAD

**Issue by fashioncj** [moyix/panda#37]
i try it instead the long command,it is very simple.
but when i use it at api level 16,it seems has some problems.

    line103:
    if args.api_level > 18: # higher than 4.3
    # have the NAND pretend to be a block device for ext4
    fake_block_device = True 

when`api_level`is 16 but it still worked.

---
and the `-S` maybe removed or in some args.

**Comment by moyix** [comment]
Could you clarify what problems you had with API level 16? I.e. what was supposed to happen vs what actually happened?

**Comment by fashioncj** [comment]
using command `...py /PATH/ 16` the correct command should be whitout `ext4` options but when I using this command it out put the `ext4=on`

**Comment by fashioncj** [comment]
@moyix the wrong in python 2,the `args.api_level` is char ,so it must bigger number 18
the right code should be:

    if args.api_level > '18': # higher than 4.3
        # have the NAND pretend to be a block device for ext4
        fake_block_device = True
    if args.api_level > '12': # higher than 3.1
        # use ARMv7 CPU
        cpu = "cortex-a9"

**Comment by moyix** [comment]
Ok, I think I see the problem. I think the right fix is to change line 63 like so:

`parser.add_argument("api_level", type=int)`

Which will correctly convert the argument.

@jhodosh, can you confirm?
