### ISSUE TITLE
android taint support

### ISSUE THREAD

**Issue by Epeius** [moyix/panda#5]
Hi,
I find PANDA is a great analysis platform since it supports many archs, so I want to do some Android taint analysis experiments with PANDA's taint analysis plugin-PIRATE. But I found that in taint.cpp there was a function called "guest_hypercall_callback()", which invoked the "enable_taint()" function. But in guest_hypercall_callback(), code seems to not support ARM as follows:
int guest_hypercall_callback(CPUState *env){
#ifdef TARGET_I386
    target_ulong buf_start = env->regs[R_EBX];
    target_ulong buf_len = env->regs[R_ECX];
    if (env->regs[R_EAX] == 7 || env->regs[R_EAX] == 8){
        if (!taintEnabled){
            printf("Taint plugin: Label operation detected\n");
            printf("Enabling taint processing\n");
            taintJustEnabled = true;
            taintEnabled = true;
            enable_taint();
        }
#endif // TARGET_I386
    return 1;
}

So, it seems that this taint plugin doesn't support ARM platform, or on ARM, there is anthor way to start analysis?

Best regards.
B. Zhang

**Comment by 2048li** [comment]
I have the same question,anybody answers?
Thanks!

**Comment by rjwhelan** [comment]
See arm_hypercall_callback() in panda_plugins/taint/taint.cpp.  Also, see panda_tools/pirate_utils/linux/pirate_mark.h.  This header file provides code that you can run inside the VM to perform labeling.

**Comment by 2048li** [comment]
Thanks!
