### ISSUE TITLE
Memory callbacks interfere with other callbacks

### ISSUE THREAD

**Issue by volpino** [moyix/panda#50]
I noticed that if in a plugin I use PANDA_CB_VIRT_MEM_WRITE and PANDA_CB_VIRT_MEM_READ alone they work fine. However if I add another callback like PANDA_CB_BEFORE_BLOCK_TRANSLATE either the memory callbacks work or the before_block_translate one, but not all of them together. The final behavior is determined by the order in which I call panda_register_callback().

Is this due to the fact that panda_enable_memcb() adds some callbacks? My final goal is just to get the address of the basic block that is being executed when a memory operation is performed, so if there is another way that does not involve adding other callbacks, apart from memory read/write, it is ok for me.

Thank you

**Comment by moyix** [comment]
I'm not able to reproduce this. Using a plugin that looks like

    target_ulong current_bb;

    int before_block_exec(CPUState *env, TranslationBlock *tb) {
        current_bb = tb->pc;
        return 0;
    }

    int vmem_write(CPUState *env, target_ulong pc, target_ulong addr, target_ulong size, void *buf) {
        printf("Current BB " TARGET_FMT_lx " write to " TARGET_FMT_lx "\n", current_bb, addr);
        return 0;
    }

    bool init_plugin(void *self) {
        panda_enable_memcb();

        panda_cb pcb;
        pcb.before_block_exec = before_block_exec;
        panda_register_callback(self, PANDA_CB_BEFORE_BLOCK_EXEC, pcb);
        pcb.virt_mem_write = vmem_write;
        panda_register_callback(self, PANDA_CB_VIRT_MEM_WRITE, pcb);

        return true;
    }

I get output like:

    Current BB 0000000090f2b48f write to 000000009315f62b
    Current BB 0000000090f2b57a write to 000000009315fb2d
    Current BB 0000000090f28cf5 write to 000000009315f8d8
    ...

Which indicates to me that it is correctly updating `current_bb` and tracking memory writes.

What does the registration code for your plugin look like?

**Comment by volpino** [comment]
With your order of registering callbacks it works.

If I use something like:

    panda_cb pcb;
    pcb.before_block_exec = before_block_exec;
    pcb.virt_mem_write = vmem_write;
    panda_register_callback(self, PANDA_CB_VIRT_MEM_WRITE, pcb);
    panda_register_callback(self, PANDA_CB_BEFORE_BLOCK_EXEC, pcb);

Then before_block_exec is never called and when I try to access the data buffer in vmem_write I get a segfault (not always, in my case after a couple of calls of the callback).

If instead I use something like

    panda_cb pcb;
    pcb.virt_mem_write = vmem_write;
    pcb.before_block_exec = before_block_exec;
    panda_register_callback(self, PANDA_CB_VIRT_MEM_WRITE, pcb);
    panda_register_callback(self, PANDA_CB_BEFORE_BLOCK_EXEC, pcb);

Then before_block_exec is called but still vmem_write segfaults when accessing the buffer

I think there was also some other ordering that caused the vmem_write to not being called, but I cannot reproduce it anymore.

Anyway with the order you suggested it works :)

**Comment by moyix** [comment]
Ah, I see the problem: `panda_cb` is a union, not a struct. So when you do

    pcb.virt_mem_write = vmem_write;
    pcb.before_block_exec = before_block_exec;

You are just overwriting the vmem_write pointer with before_block_exec.
