### ISSUE TITLE
about begin_record : vm will resume

### ISSUE THREAD

**Issue by 2048li** [moyix/panda#52]
Hi,
Thanks for your guys work first!
Now my question is: when I tried process described in the docs/panda_ssltut.md,I was confused about "Taking the snapshot can take a long time.once the snapshot is made, the vm will resume." Is it means that I must wait till the vm resume?and then i can take the next step?
But I have stayed this step for a long time,it seems not to resume.it just shows"opening nondet log for write:.****.log"
Thanks for checking!
Any suggestions?
Thanks a lot!

**Comment by volpino** [comment]
I think the tutorial is not up-to-date, on my machine the begin_record command is almost instant. Are you sure the machine stays "stopped"? Cause the prompt is not shown again after the command but if you press enter it appears.
Hope this helps

**Comment by 2048li** [comment]
Thanks first!
I means that when I input begin_record,it just stayed in "opening nondet log for write" and there was no   message indicating that the write action was done.When I press enter it just the same state.

**Comment by volpino** [comment]
I cannot reproduce your issue, for me it works well with the last version of PANDA.
Maybe you can try to spot the problem by looking at the snapshot file that PANDA creates, if it's growing then it is still being created. Also, is the machine actually stopped or is it running?
Anyway I think the developers can give you better answers. Good luck!

**Comment by 2048li** [comment]
The machine just keeps its state for a long time.I will try another way.
Thanks a lot~

**Comment by moyix** [comment]
I think this has been answered on the mailing list now.
