### ISSUE TITLE
about android taint on arm

### ISSUE THREAD

**Issue by 2048li** [moyix/panda#55]
Hi,
I have a question about taint:
in the paper——Repeatable Reverse Engineering for the Greater Good with PANDA the "Taint analysis" part, you have used it to analysis ARM replays.
But when I build PANDA successfully, I have not find panda_taint.so(which is necessary in tainting) in /qemu/arm-softmmu/panda_plugins as well in /i386-softmmu/panda_plugins.And README.md which is included in taint directory says that "hard device and network taint is now supported for x86/64 systems".
How do you use taint plugin to analysis arm system?
Thanks a lot!

**Comment by m000** [comment]
Make sure you have enabled LLVM support as described in the installation documentation. Without LLVM support, the following block in the Makefile of the taint plugin is not activated. So you have no `all` target.

```
ifdef CONFIG_LLVM
all: $(PLUGIN_TARGET_DIR)/panda_$(PLUGIN_NAME).so
endif
```

You may want to add some debug printout in this block to see if it is activated or not.

**Comment by 2048li** [comment]
I used the build.sh and I checked it including"--enable-llvm".

**Comment by m000** [comment]
Can you provide a list of steps to reproduce the problem?
Otherwise we can only give you educated guesses and it is a matter of time before the issue is closed.

**Comment by 2048li** [comment]
Thanks a lot! I find its problem!
And I am puzzled about the PATH used in makefile or something like.
