### ISSUE TITLE
Documentation for plugins

### ISSUE THREAD

**Issue by moyix** [moyix/panda#6]
We need some documentation for existing plugins. Some have a bit already, such as the [taint plugin](https://github.com/moyix/panda/blob/master/qemu/panda_plugins/taint/README.md), but most are completely undocumented.

**Comment by volpino** [comment]
What is the difference between taint and taint2? And between syscall and syscall2?

I can understand that it requires time to document everything and sometimes just the name, reading the code or the comments in there give enough information. But in those cases at least a more meaningful name or one line that states why there is another version of the same plugin would be appreciated.

**Comment by m000** [comment]
Would it make sense to move some of the older plugins in a `panda_plugins/deprecated` directory?
Anyone who wishes to try them out he can find them there. The rest will see the up-to-date versions by default.

**Comment by moyix** [comment]
That's probably a good idea. For syscalls at least, it has been fully replaced by syscalls2. With taint2 vs taint, I believe taint2 is still missing some features like HDD / network taint.

**Comment by phulin** [comment]
Yes - taint2 is still under pretty rapid development. We still need to add
hdd/network taint, and we still need to fix some algorithm/data structure
issues (i.e. performance) issues.
