### ISSUE TITLE
build.sh fails with an AttributeError for ArrayDecl

### ISSUE THREAD

**Issue by stkerr** [moyix/panda#61]
I followed the directions on how to build Panda and got everything built. When I run build.sh however, I get the following error:

```
skerr@gravel:~/panda/qemu$ ./build.sh 
Building API for plugin sample
Traceback (most recent call last):
  File "../scripts/apigen.py", line 198, in <module>
    generate_api(plugin, plugin_dir)
  File "../scripts/apigen.py", line 164, in generate_api
    arglist = get_arglists(pf)
  File "../scripts/apigen.py", line 33, in get_arglists
    for arg in fundec.args.params:
AttributeError: 'ArrayDecl' object has no attribute 'args'
skerr@gravel:~/panda/qemu$ 
```

Could this be from Pycparser being updated since the directions were written or some other script updated? The function it is struggling to process is 'sample_function'.

**Comment by stkerr** [comment]
Note I was able to resolve this by removing the pycparser that I built directly from the GitHub repository and instead installed it with pip.

I suggest updating the documentation to recommend using pip instead of building by hand, though I am willing to listen if there is a specific reason to build it from source.

**Comment by phulin** [comment]
This has been fixed.
