### ISSUE TITLE
Build panda qemu error with run CC=gcc-4.8 CXX=g++-4.8 ./build.sh

### ISSUE THREAD

**Issue by guanxianchun** [moyix/panda#73]
I followed the directions on how to build Panda and got everything built. When I run build.sh(root@ubuntu:/home/panda/panda/qemu# CC=gcc-4.8 CXX=g++-4.8 ./build.sh
) however, I get the following error:
In file included from taint_ops.cpp:28:
In file included from /home/panda/panda/llvm/include/llvm/IR/Constants.h:24:
In file included from /home/panda/panda/llvm/include/llvm/ADT/APFloat.h:104:
In file included from /home/panda/panda/llvm/include/llvm/ADT/APInt.h:18:
In file included from /home/panda/panda/llvm/include/llvm/ADT/ArrayRef.h:14:
In file included from /home/panda/panda/llvm/include/llvm/ADT/SmallVector.h:17:
/home/panda/panda/llvm/include/llvm/Support/AlignOf.h:19:10: fatal error: 'cstddef' file not found
#include <cstddef>
         ^
1 error generated.
make[2]: *** [/home/panda/panda/qemu/arm-softmmu/panda_plugins/panda_taint2/llvm_taint_ops.bc] Error 1
make[1]: *** [plugin-taint2] Error 2
make[1]: *** Waiting for unfinished jobs....
  CXX   /home/panda/panda/qemu/i386-softmmu/panda_plugins/llvm_taint_lib.o
  CXX   /home/panda/panda/qemu/x86_64-softmmu/panda_plugins/taint.o
  CXX   /home/panda/panda/qemu/x86_64-softmmu/panda_plugins/llvm_taint_lib.o
  PLUGIN  /home/panda/panda/qemu/arm-softmmu/panda_plugins/panda_taint.so
make: *** [subdir-arm-softmmu] Error 2
make: *** Waiting for unfinished jobs....
  PLUGIN  /home/panda/panda/qemu/i386-softmmu/panda_plugins/panda_taint.so
make: *** [subdir-i386-softmmu] Error 2
  PLUGIN  /home/panda/panda/qemu/x86_64-softmmu/panda_plugins/panda_taint.so
make: *** [subdir-x86_64-softmmu] Error 2

**Comment by moyix** [comment]
Could you make sure you have `libc++-dev` installed?

**Comment by guanxianchun** [comment]
Thank you for replay. I have solved this problem.
