### ISSUE TITLE
taint2 plugin breaks build for g++-4.9

### ISSUE THREAD

**Issue by m000** [moyix/panda#74]
I get this error when building PANDA using g++/gcc v4.9. The error occurs when compiling `taint_ops.cpp` using clang.

```
In file included from taint_ops.cpp:28:
In file included from /home/user/panda/llvm/include/llvm/IR/Constants.h:24:
In file included from /home/user/panda/llvm/include/llvm/ADT/APFloat.h:104:
In file included from /home/user/panda/llvm/include/llvm/ADT/APInt.h:18:
In file included from /home/user/panda/llvm/include/llvm/ADT/ArrayRef.h:14:
In file included from /home/user/panda/llvm/include/llvm/ADT/SmallVector.h:17:
In file included from /home/user/panda/llvm/include/llvm/Support/AlignOf.h:19:
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../../include/c++/4.9/cstddef:51:11: error: no member named 'max_align_t' in the global namespace
  using ::max_align_t;
        ~~^
```

**Comment by m000** [comment]
A [clang patch](http://reviews.llvm.org/rL201729) has been submitted which fixed the problem for me. Of course this meant recompiling LLVM.
I added instructions to `compile.md` for applying the patch. See: 0010020834c6429bdd8872c72f86cacda6ad48e7

**Comment by phulin** [comment]
I thought I had fixed this but clearly not. Thanks.

On Monday, July 27, 2015, Manolis Stamatogiannakis <notifications@github.com>
wrote:

> A clang patch <http://reviews.llvm.org/rL201729> has been submitted which
> fixed the problem for me. Of course this meant recompiling LLVM.
> I added instructions to compile.md for applying the patch. See: 0010020
> <https://github.com/moyix/panda/commit/0010020834c6429bdd8872c72f86cacda6ad48e7>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/moyix/panda/issues/74#issuecomment-125399779>.
>


-- 
Sent using a stone tablet and chisel. Please excuse the brevity.
