### ISSUE TITLE
scissors plugin exits with "ERROR: replay failed"

### ISSUE THREAD

**Issue by 0xABD** [moyix/panda#81]
Using the April PANDA VM published in the PANDA blog (pandavm-20150413.tar.bz2) I have made a recording of an android target approx. 2.3 billion instructions long (the recording files are ~450 MB snapshot and a ~5 MB log).

The issue scenario is as follows:

1. I verify that the captured replay is correct by running it again and again and watching it complete without errors.
2. Using the "stringsearch" plugin on the replay, I identify an interesting region in the recording that is approx. its last 10% (from ~2.1 G instructions to ~2.28 G instructions)
3. I copy the start and end GIC values from the stringsearch output, and then run the replay with various start and end values.
    * if start ~2.1G and end ~2.28 G (the range I really need) I always get **"ERROR: replay failed"** at the precise moment the execution reaches the GIC specified in the 'start' parameter. 
    * Then I try to narrow down the problematic GIC range.
        * if start == 1000000 and end == 2000000, the scissors work
        * if start == 10000000 and end == 20000000, it crashes with a **segfault**
        * if start == 100000000 and end == 200000000, it reports **"ERROR: replay failed"** when the GIC = 99999998 
        * if start == 0 and end ~2.1G, the scissors work
        * if start == 0 and end ~2.2G, the scissors work
        * if start == 100000000 and end ~2.2G, the scissors work
        * if start ~1G and end ~2.2G, it reports **"ERROR: replay failed"** when the GIC is slightly less than 1G

Please advise on how to debug and resolve such an issue.

**Comment by moyix** [comment]
Would it be possible to pack up the log file (using rrpack) and post it somewhere along with the command line used for the replay so we can reproduce & fix?

**Comment by 0xABD** [comment]
Hi, thank you for the response, unfortunately it is not possible to get any data at all from the target environment. 
I will try to reproduce the issue on a newer October VM and report here.

**Comment by 0xABD** [comment]
Captured the whole run on an October 2015 VM, the scissors worked.
Thank you, now closing the issue.
