### ISSUE TITLE
don't compile panda/qemu/panda/tainted_instr.cpp

### ISSUE THREAD

**Issue by larogtek12** [moyix/panda#86]
I do command 
g++ -g -o tainted_instr tainted_instr.cpp pandalog.c pandalog.pb-c.c  -L/usr/local/lib -lprotobuf-c -I .. -lz -D PANDALOG_READER -std=c++11

and see

/qemu/panda$ g++ -g -o tainted_instr tainted_instr.cpp pandalog.c pandalog.pb-c.c  -L/usr/local/lib -lprotobuf-c -I .. -lz -D PANDALOG_READER -std=c++11
tainted_instr.cpp: In function 'int main(int, char**)':
tainted_instr.cpp:54:36: error: 'Panda__LogEntry' has no member named 'n_callstack'
tainted_instr.cpp:55:22: error: 'Panda__LogEntry' has no member named 'taint_query_unique_label_set'
tainted_instr.cpp:56:22: error: 'Panda__LogEntry' has no member named 'taint_query'
tainted_instr.cpp:70:22: error: 'Panda__LogEntry' has no member named 'n_callstack'
tainted_instr.cpp:71:61: error: 'Panda__LogEntry' has no member named 'n_callstack'
tainted_instr.cpp:73:34: error: 'Panda__LogEntry' has no member named 'n_callstack'
tainted_instr.cpp:74:50: error: 'Panda__LogEntry' has no member named 'callstack'
tainted_instr.cpp:75:36: error: 'Panda__LogEntry' has no member named 'n_callstack'
tainted_instr.cpp:84:22: error: 'Panda__LogEntry' has no member named 'taint_query_unique_label_set'
tainted_instr.cpp:85:88: error: 'Panda__LogEntry' has no member named 'taint_query_unique_label_set'
tainted_instr.cpp:87:34: error: 'Panda__LogEntry' has no member named 'taint_query_unique_label_set'
tainted_instr.cpp:88:41: error: 'Panda__LogEntry' has no member named 'taint_query_unique_label_set'
tainted_instr.cpp:93:18: error: 'Panda__LogEntry' has no member named 'taint_query'
tainted_instr.cpp:94:42: error: 'Panda__LogEntry' has no member named 'taint_query'

May be I something do wrong but I think it is because of the lack of initialization in panda/qemu/panda_plugins/tainted_instr/tainted_instr.proto.

**Comment by richardracko** [comment]
Hi,

have you resolved this issue? I have the same problem and I can't find solution. Could you please help?

Thanks,
Richard

**Comment by larogtek12** [comment]
I am forgot  how fix it, but seems I downloaded last version and compiled from scratch

**Comment by foobar-x** [comment]
I have this problem too! How to fix it?
