### ISSUE TITLE
debug code don't compile

### ISSUE THREAD

**Issue by larogtek12** [moyix/panda#87]
OS - Debian 7
code version - last commit

   1. download, extract and run panda_install.bash - ok
   2. qemu/configure --enabled-debug                     - ok
   3. make                                                                 - error

.....
  CC    i386-softmmu/kvmclock.o
  LINK  i386-softmmu/qemu-system-i386
/usr/bin/ld: panda/tubtf.o: relocation R_X86_64_32 against `.rodata' can not be used when making a shared object; recompile with -fPIC
panda/tubtf.o: could not read symbols: Bad value
collect2: error: ld returned 1 exit status
make[1]: *** [qemu-system-i386] Error 1
make: *** [subdir-i386-softmmu] Error 2

**Comment by moyix** [comment]
I'm not able to reproduce this. Not that you should not be running QEMU's ./configure directly; instead you should be using the build.sh script. If I add `--enable-debug` to the configure line that script and then run `./build.sh`, QEMU compiles just fine, so I can't reproduce on this end.

Could you try doing `make clean` and then building with `./build.sh` and see if it works?

**Comment by larogtek12** [comment]
Thank you very much, it really helped to compile the code in debug mode!
But my problem is, unfortunately, not been solved .. Why I wanted to compile in debug mode? When to debug plugins, sometimes I cannot see the value of a variable

Example 
(gdb) p a
$1 = {typ = LADDR, val = {ha = 0, ma = 0, ia = 0, pa = 0, la = 0, gr = 0, gs = 0, ua = 0, con = 0, ret = 0}, off = 0, flag = 0}
(gdb) p ao
$2 = {typ = LADDR, val = {ha = <optimized out>, ma = <optimized out>, ia = <optimized out>, pa = <optimized out>, la = <optimized out>, gr = <optimized out>, gs = <optimized out>, ua = <optimized out>, 
    con = <optimized out>, ret = <optimized out>}, off = 0, flag = <optimized out>}
(gdb) p num_tainted 
$3 = <optimized out>

I have read that it is possible to solve the problem if compiled without optimization and debug mode. But I had compiled in debug mode and it did not help.

---------------------------------------------------
And I would like to ask about a some bug (but again may be, I something not so I do).
	0. OS - Clear Debian 8.3 with all updates
	1. Download from github PANDA, I unpack and run ./panda_install.bash 
	2. LLVM and distorm didn't install
	 - part of the output from the log./panda_install.bash
	...
	[panda_install] Trying to install LLVM 3.3...
	Reading package lists... Done
	Building dependency tree       
	Reading state information... Done
	Package clang-3.3 is not available, but is referred to by another package.
	This may mean that the package is missing, has been obsoleted, or
	is only available from another source
	However the following packages replace it:
	  clang-3.5 clang-3.4 clang

	E: Unable to locate package llvm-3.3-dev
	E: Couldn't find any package by regex 'llvm-3.3-dev'
	E: Package 'clang-3.3' has no installation candidate

	[panda_install] Couldn't find OS package for LLVM 3.3. Proceeding without...
	...
	
	- # ls -lsa (PANDA's dir)
		total 76
		 4 drwx------  8 panda panda  4096 Feb  6 07:05 .
		 4 drwxr-xr-x 35 panda panda  4096 Feb  3 08:44 ..
		 4 drwx------  3 panda panda  4096 Feb  3 03:44 docs
		 4 -rw-r--r--  1 panda panda  2056 Jan 11 18:27 .gitignore
		 4 drwxr-xr-x 17 panda panda  4096 Feb  3 05:09 llvm
		 4 -rw-r--r--  1 panda panda  2504 Jan 11 18:27 panda-comment.py
		 4 -rwxr-xr-x  1 panda panda  2300 Jan 11 18:27 panda_install.bash
		 4 -rw-r--r--  1 panda panda    45 Jan 11 18:27 provision.sh
		20 drwx------ 97 panda panda 20480 Feb  6 07:14 qemu
		 4 -rw-r--r--  1 panda panda  3778 Jan 11 18:27 README.md
		 4 drwx------  2 panda panda  4096 Feb  3 03:44 scripts
		 4 drwx------  3 panda panda  4096 Feb  3 03:44 testing
		 4 -rw-r--r--  1 panda panda   388 Jan 11 18:27 .travis.yml
		 4 -rw-r--r--  1 panda panda  1222 Jan 11 18:27 Vagrantfile
		 4 drwx------  2 panda panda  4096 Feb  3 03:44 volatility
		 
	How had I solved this problem?
	1. I creates in panda's directory - directory  llvm
	2. to copy the source code and compiled llvm 3.3
	3. in the directory ..panda/llvm/Release/bin symlink to do ../panda/llvm/include
	4. It is work. But I suspect that, it can be made easier.

**Comment by m000** [comment]
@ larogtek12 clang/llvm 3.3 seem to have been obsoleted by debian. You may want to try the old compile instructions which describe how to compile llvm/clang source: https://github.com/moyix/panda/blob/17192b36e4967f43df12f93056f44cdb68db7e27/docs/compile.md

@moyix This is why I argued against killing compile.md. IMHO the compile.md + build.sh combo was more reliable and easier to provide help on any problems.

**Comment by moyix** [comment]
The LLVM compile instructions are still around:

https://github.com/moyix/panda/blob/master/docs/manual.md#building-llvm

In any case, @m000, I agree with you – we should restore the compile instructions (with some updating to fix the C++ ABI issues).

**Comment by moyix** [comment]
@larogtek12 – to answer your question about getting debug symbols enabled and getting rid of the `<optimized out>` messages, you may want to try editing `build.sh` and changing

```
--extra-cflags="-O2 -I/usr/local/include" \
--extra-cxxflags="-O2" \
```

To use `-O0` instead. This will of course make things slower but it should be easier to debug. You may also want to include `-ggdb` there to make sure it's emitting gdb debug information.

**Comment by larogtek12** [comment]
Thank you very much for your answers! With your help, I could compile panda with llvm.
But there was new another problem. (I honestly do not know how I get so :) )

When I compiled the panda and tried to run, I did not succeed. Here's how it looks.

```
panda@panda:~/panda2/qemu/x86_64-softmmu$ ./qemu-system-x86_64 -m 1024 -replay syscal2
loading snapshot
qemu: warning: error while loading state for instance 0x0 of device 'ram'
qemu-system-x86_64: Error -5 while loading VM state
... done.
opening nondet log for read :	./syscal2-rr-nondet.log
Infinite loop detected during replay, aborting.
{guest_instr_count=0 pc=0x0000fff0, secondary=0x00000000}
syscal2:           0 (  0.00%) instrs.    1.51 sec.  0.17 GB ram.
total_instr in replay:  541296124
ERROR: replay failed!
Time taken was: 0 seconds.
max_queue_len = 1
0 items on recycle list, 0 bytes total
ERROR: replay failed!
Aborted
```

Just I tried to download and put the panda with the repository, without changing anything. (on the same Debian 8 system), still the same error.

Although I ran to the other systems, and all went well. Perhaps as it is not properly set up qemu, I do not know... Could you help with it ?

That's why I can not test until disable optimized mode.

P.S. may be need log and snapshot. here -> https://www.dropbox.com/s/ibup8ryj03ltsfk/syscal2.rar?dl=0

**Comment by moyix** [comment]
Check that the snapshot (the `syscal2-rr-snp` file) was copied into the virtual machine fully. `-5` is `EIO`, an input/output error. Usually this means that the file was truncated or corrupt somehow. Could you compare the MD5 and file size of the snapshot on the Debian 8 system with the file on the system where it works?

**Comment by larogtek12** [comment]
Thanks again for your reply, yes you, you were right. I copy the correct version and start run normally. But.

Here are just out of nowhere appeared another one problem...)

1) ОС  is the same
2) unpacked panda
3) compiled llvm
4) copied snp, log , stringsearch file
5)  launched run - ./qemu-system-x86_64 -m 1024 -replay syscal2
 it's ok
6) launched run - ./qemu-system-x86_64 -m 1024 -replay syscal2 -panda 'tstringsearch'
 error
 
```

..
syscal2:   265683291 ( 49.08%) instrs.   62.36 sec.  0.53 GB ram.
READ Match of str 0 at: instr_count=267453709 :  00000000805c7045 000000008050fd8e 0000000000000000
tstringsearch: thestring = [.n.g]
tstringsearch: 00 6e 00 67 
WRITE Match of str 0 at: instr_count=267453709 :  00000000805c7045 000000008050fd90 0000000000000000
tstringsearch: thestring = [pin.]
tstringsearch: 70 69 6e 00 
tstringsearch: string in memory @ 0x8620c9e4
enabling taint at instr count 267453709
taint2: __taint_enable_taint
taint2: Creating byte-level taint processor
taint2: Allocating large fast_shad (17179869184 bytes).
taint2: Hugetlb failed. Trying without.
Cannot allocate memory
taint2: Allocating small fast_shad (12800000 bytes) using malloc @ 7fff322fe010.
taint2: Allocating small fast_shad (256 bytes) using malloc @ 7fff2b120770.
taint2: Allocating small fast_shad (2560 bytes) using malloc @ 7fff2b037c40.
taint2: Allocating small fast_shad (912896 bytes) using malloc @ 7fff3221f010.
taint2: Linking taint ops from /home/panda/panda3/qemu/x86_64-softmmu/panda_plugins/panda_taint2_ops.bc
taint2: Done initializing taint transformation.
taint2: Note: unsupported intrinsic llvm.lifetime.start in cpu_x86_inject_mce_llvm.
taint2: Note: unsupported intrinsic llvm.lifetime.end in cpu_x86_inject_mce_llvm.
taint2: Done processing helper functions for taint.
taint2: Done verifying module. Running...

****************************************************************************
applying taint labels to search string of length 4  @ p=0x000000008620c9e4
******************************************************************************

Program received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff74755700 (LWP 35655)]
label (ls=<optimized out>, addr=<optimized out>, this=<optimized out>) at fast_shad.h:123
123	        *get_td_p(addr) = TaintData(ls);
```

Tried 4 times, each time from scratch - unpack the archive panda, compiled llvm and build panda. The result is same

**Comment by moyix** [comment]
The key lines are:

```
taint2: Hugetlb failed. Trying without.
Cannot allocate memory
```

The taint system allocates a memory region 16x larger than the guest RAM. So the if the host doesn't have that much memory available it will fail. We should make this a bit less confusing (i.e. error message not crash).
