### ISSUE TITLE
Replay failure (rr_log.c:1027 assertion failed error, FOUND DISAGREEMENT! error)

### ISSUE THREAD

**Issue by aufa35** [moyix/panda#91]
Hi, I am learning how to use Panda's replay feature. After about 1/8 of instructions is replayed, repay stops with an error:

> RR rr_assertion `0' failed at /home/panda/panda/qemu/rr_log.c:1027
Current log point:
{guest_instr_count=1440464191 pc=0x806e73c2, secondary=0x000000ff}
Next log entry type: RR_INPUT_4
Current replay point:
{guest_instr_count=1440464175 pc=0x806e7f2d, secondary=0x00000000}

Host: PANDA VM October 2015 (Debian)
Guest: Windows XP 2002 SP3 (qcow2 format created by qemu-img with `-o compat=0.10`)

Run qemu terminal command: `/home/panda/panda/qemu/x86_64-softmmu/qemu-system-x86_64 -drive file=/home/panda/qcow/winXp-compat.qcow2,if=ide,cache=writeback -m 1024M -spice port=5001,disable-ticketing -vga qxl -monitor stdio`

(then `begin_record test2` to terminal, and `end_record`)

Replay qemu terminal command: `home/panda/panda/qemu/x86_64-softmmu/qemu-system-x86_64 -drive file=/home/panda/qcow/winXp-compat.qcow2,if=ide,cache=writeback -m 1024M -vga qxl -monitor stdio -replay test2`

I can start Windows XP with panda, problem is only with replay. Could you help me? 

Record:
http://www.filedropper.com/test2-rr-snp
http://www.filedropper.com/test2-rr-nondet

I tried record new record and replay it. After 7% of record I got another error:

> Ahead of log while looking for log entry of type RR_INPUT_4
{guest_instr_count=892953525 pc=0x806e79f0, secondary=0x8671d414}
	RR_INPUT_4 from RR_CALLSITE_IO_READ_2
FOUND DISAGREEMENT!
Replay program point:
{guest_instr_count=892953530 pc=0x806e79f0, secondary=0x8658d14c}

>Record program point:
{guest_instr_count=892953525 pc=0x806e79f0, secondary=0x8671d414}

>\>>> guest instruction counts disagree
>\>>> guest secondary info disagrees
ERROR: replay failed!

**Comment by moyix** [comment]
Could you try doing the recording under VNC or SDL for video? I'm not familiar with how the spice video works in QEMU and it's possible it contains some kind of nondeterminism we aren't capturing.

**Comment by aufa35** [comment]
Probably the problem was that I was using x64 qemu system for 32 bit windows XP. When I tried it with i386, record and replay was working. Also Spice may be not problem, under i386 I could record/replay 32bit windows 7 with spice video.
I would have another question (should I open new issue?). When I try to replay 18seconds long windows 7 record with plugins 'asidstory;osi;win7x86intro' it consumes amazing amount of RAM. In 7% of replay Panda consumes 4 GB of RAM and then my OS kills Panda.

**Comment by moyix** [comment]
This is a bug in the version of PANDA that comes with that VM and has since been fixed (see commit aa7b980b580fb0116455cdcac4f4c15fd0345458). You can run `git pull` and then `./build.sh` to rebuild and it should fix the memory leak.

**Comment by aufa35** [comment]
Thank you ;-)

**Comment by Irkam** [comment]
I'm having the same problem with latest build when running Android 19 guest (from scripts/runandroid.py's generated foobar-rr.cmd) on an Ubuntu 14.04 host.

spoiler : Command line is huge : 

`~/panda/qemu$ arm-softmmu/qemu-system-arm -M android_arm -cpu cortex-a9 -kernel /home/jean-vincent/training/panda/pandroid/kernel -initrd /home/jean-vincent/training/panda/pandroid/initramfs -global goldfish_nand.system_path=/home/jean-vincent/training/panda/pandroid/system-pandroid.qcow2 -global goldfish_nand.user_data_path=/home/jean-vincent/training/panda/pandroid/data-pandroid.qcow2 -global goldfish_nand.cache_path=/home/jean-vincent/training/panda/pandroid/cache-pandroid.qcow2 -append "console=ttyS0 ndns=2 qemu=1 no_console_suspend=1 qemu.gles=0 android.qemud=ttyS1" -m 2G -no-reboot -monitor telnet:localhost:4321,server,nowait -show-cursor -serial stdio -serial telnet:localhost:4421,server,nowait -display sdl -global goldfish_mmc.sd_path=/home/jean-vincent/training/panda/pandroid/sdcard.qcow2 -android -S -net nic,vlan=1 -net user,vlan=1 -global goldfish_nand.ext4=on -replay foobar`

(told you)

Now this command line works well when the `-replay foobar` part is stripped, but when I add it and push `c`to the monitor console, i get this output :

```
RR rr_assertion `0' failed at /home/jean-vincent/panda/qemu/rr_log.c:1061
Current log point:
{guest_instr_count=10105 pc=0xc02108e4, secondary=0x00000000}
Next log entry type: RR_INPUT_4
Current replay point:
{guest_instr_count=10105 pc=0xc0210830, secondary=0x00000000}
```

This happens the same way whether I'm recording from the start, or just the 12 seconds that interest me. Maybe this is just related to Pandroid but i'm not sure right now.

**Comment by phulin** [comment]
Have you tried running without all the devices? All you should need to pass is -M android_arm -cpu cortex-a9 -m 2G to get it to replay. I think. I haven't really used the Android stuff.

**Comment by phulin** [comment]
Also, I should mention that replay failures are pretty tricky to debug. If you want to dive in, you can run both record and replay under Mozilla RR and see where the guest execution diverges - and then trace that back to some un-replayed source of nondeterminism. The error message usually doesn't (can't) point you to the exact root cause.

**Comment by moyix** [comment]
I agree with @phulin that it may be a good idea to try with fewer devices. I *think* the minimum needed is 

```
../arm-softmmu/qemu-system-arm -m 2048 -replay line2 -M android_arm -android -cpu cortex-a9 -kernel /dev/null \
  -global goldfish_mmc.sd_path=/dev/null -global goldfish_nand.system_path=dummy2.qcow2 \
  -global goldfish_nand.user_data_path=dummy.qcow2'
```

(command line taken from the LINE tutorial). Could you try something like that and see if it works?

**Comment by Irkam** [comment]
From what I've done so far, I never managed to complete the LINE because of an infinite loop. But anyway let's try this :)

The machine would not run without `-kernel` so I set it to `/dev/null` just like in LINE tutorial. The resulting command line is 

`~/panda/qemu$ arm-softmmu/qemu-system-arm -M android_arm -cpu cortex-a9 -kernel /dev/null -global goldfish_nand.system_path=system-pandroid.qcow2 -global goldfish_nand.user_data_path=data-pandroid.qcow2 -m 2G -global goldfish_mmc.sd_path=/dev/null -replay foobar`

And this outputs the same result as the tutorial :

```
opening nondet log for read :	./foobar-rr-nondet.log
Infinite loop detected during replay, aborting.
{guest_instr_count=1 pc=0x00000004, secondary=0x00000000}
foobar:           1 (  0.00%) instrs.    1.21 sec.  2.05 GB ram.
total_instr in replay:  123211651
ERROR: replay failed!
Time taken was: 0 seconds.
max_queue_len = 1
```

BUT it outputs the same as previously when adding the `-android` flag.


As @phulin said I may take a look at Mozilla RR, see if I can get more outputs, wish me luck !

**Comment by Irkam** [comment]
Small update : I performed the same procedure on a Debian Wheezy ARM (one of [these](https://people.debian.org/~aurel32/qemu/armel/) images, converted with `-compat=0.10` and run with the recommended args) and ran on the exact same output as with Android. 

The command lines I used are 

`~/panda/qemu/arm-softmmu/qemu-system-arm -M versatilepb -kernel vmlinuz-3.2.0-4-versatile -initrd initrd.img-3.2.0-4-versatile -hda debian_wheezy_armel_compat.qcow2 -monitor stdio -replay foobarbaz`

and 

`~/panda/qemu/arm-softmmu/qemu-system-arm -M versatilepb -kernel /dev/null -hda Cdebian_wheezy_armel_compat.qcow2 -monitor stdio -replay foobarbaz`

I'm starting to think this has something to do with ARM RRs.

**Comment by moyix** [comment]
Which image specifically were you using? Standard or desktop? I'll try to reproduce.

**Comment by moyix** [comment]
And indeed, I can confirm that ARM recordings are broken by the changes introduced after 38e9caf. So for now you should roll back and we'll get it fixed.

**Comment by Irkam** [comment]
I'm rolling on a fork from 5697671 with the standard image (the desktop was too heavy to download). I'm not on my battlestation right now so I'll give it a shot when I can ;)

**Comment by Irkam** [comment]
I rolled back to 38e9caf, made new recordings, and it worked like a charm ! Thank you again :D

**Comment by StablelJay** [comment]
I use qemu-system-i386 and windowsxp iso, but i have the same problem with u . this is my replay command  

> sudo ./qemu-system-i386 -replay notepad -m 2048 
and these are errors

> loading snapshot
... done.
opening nondet log for read :	./notepad-rr-nondet.log
main-loop: WARNING: I/O thread spun for 1000 iterations
Ahead of log while looking for log entry of type RR_SKIPPED_CALL
{guest_instr_count=9761}
	RR_INPUT_8 from RR_CALLSITE_IO_READ_ALL
FOUND DISAGREEMENT!
Replay program point:
{guest_instr_count=9762}

Record program point:
{guest_instr_count=9761}

>>> guest instruction counts disagree
notepad:        9762 (  0.00%) instrs.    0.23 sec.  0.64 GB ram.
ERROR: replay failed!
Time taken was: 0 seconds.
Stats:
RR_INPUT_1 number = 0, size = 0 bytes
RR_INPUT_2 number = 0, size = 0 bytes
RR_INPUT_4 number = 10, size = 140 bytes
RR_INPUT_8 number = 14, size = 252 bytes
RR_INTERRUPT_REQUEST number = 12, size = 168 bytes
RR_EXIT_REQUEST number = 0, size = 0 bytes
RR_SKIPPED_CALL number = 0, size = 0 bytes
max_queue_len = 9
ERROR: replay failed!

Is there any problem??

**Comment by moyix** [comment]
@StablelJay: The replay failure error message just means that it detected a divergence between the recording and the replay – this could be caused by a wide variety of issues and is probably not related. We will track your bug in Issue #146.
