### ISSUE TITLE
asidstory on debian wheezey - Segmentation fault

### ISSUE THREAD

**Issue by richardracko** [moyix/panda#92]
Hi!

When I run asidstory on replay from debian wheezey x86, it started to print asid, pc and proc entries, but after few thousands of instructions ends with Segmentation fault.

I run **asidstory** with this command:
`panda/qemu/i386-softmmu/qemu-system-i386 -m 512 -replay rec_taint -panda 'osi;osi_linux:kconf_file=kernelinfo.conf,kconf_group=wheezy;asidstory'`

On this replay I successfully run **osi_test or tainted_instr plugins:**

`panda/qemu/i386-softmmu/qemu-system-i386 -m 512 -replay rec_taint -panda 'osi;osi_linux:kconf_file=kernelinfo.conf,kconf_group=wheezy;osi_test'`

`panda/qemu/i386-softmmu/qemu-system-i386 -hda wheezy.qcow2 -m 512 -replay rec_taint -panda 'osi;osi_linux:kconf_file=kernelinfo.conf,kconf_group=wheezy;syscalls2:profile=linux_x86;file_taint:filename=/home/user/license.txt,pos,first_instr=3854039;tainted_instr:summary=true' -pandalog taint_instr_summary_true.plog`

I also created another replay to make me sure, that the **problem is not in replay itself.**

My [**kernelinfo.conf**](http://pastebin.com/z2PepLrY) was created based on tutorial [here](https://github.com/moyix/panda/blob/master/qemu/panda_plugins/osi_linux/USAGE.md)

Asidstory works on replays from Windows7 32bit without any issue.

Here is [replay](http://www.rrshare.org/detail/49/) , if you want to reproduce this issue. 

Could you please fix this?

Thanks,
Richard

**Comment by richardracko** [comment]
Hi again,

I've done following fix and I'm able to run analysis on linux now:
https://github.com/richardracko/panda/commit/9afabfabfaecb7e941fbf9c43ae15d632cd4005a

Thanks,
Richard

**Comment by moyix** [comment]
Sorry we didn't get to this earlier! It looks like the relevant printf has been removed since then, so I'll close this issue.
