### ISSUE TITLE
Cannot replay: error -22 while loading vm state

### ISSUE THREAD

**Issue by davidyoung8906** [moyix/panda#98]
Hi! 
     I get following error message when replay:

![image](https://cloud.githubusercontent.com/assets/1767219/14680988/eb732aee-06e4-11e6-926c-822c7f4a898c.png)
      
 Here's what I do when record:
    
![image](https://cloud.githubusercontent.com/assets/1767219/14681016/0bc7c30e-06e5-11e6-9d0b-50e02bacaeb9.png)

You can find my replay trace here: https://dl.dropboxusercontent.com/u/37908210/lss.rr

**Comment by phulin** [comment]
Make sure you replay with the same amount of memory as when you recorded
(in this case 1G). That's the issue here.

On Wednesday, April 20, 2016, davidyoung8906 <notifications@github.com>
wrote:

> Hi!
> I get following error message when replay:
> image
> <https://cloud.githubusercontent.com/assets/1767219/14680988/eb732aee-06e4-11e6-926c-822c7f4a898c.png>
>
>  Here's what I do when record:
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/1767219/14681016/0bc7c30e-06e5-11e6-9d0b-50e02bacaeb9.png>
>
> You can find my replay trace here:
> https://dl.dropboxusercontent.com/u/37908210/lss.rr
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/moyix/panda/issues/98>
>


-- 
Sent using a stone tablet and chisel. Please excuse the brevity.

**Comment by davidyoung8906** [comment]
Thanks for the quick response. Can you let me know which option I should use to set the memory for replay. I use "-m" but it turns out to be related to migration?

**Comment by moyix** [comment]
The -m option is correct. In your case, `./x86_64-softmmu/qemu-system-x86_64 -m 1G -replay lss` should work.

**Comment by davidyoung8906** [comment]
Thanks! However, even using the same amount of memory, it still throws the error:
![screenshot - 04202016 - 01 16 17 pm](https://cloud.githubusercontent.com/assets/1767219/14685424/3617964c-06fa-11e6-98b9-013358a8fd84.png)

**Comment by phulin** [comment]
Your guest devices on replay need to match exactly your devices during record in order to load the snapshot. This just means that if you recorded with -vga std you need to replay with that argument as well. We usually use the default devices to avoid complicated command lines during replay.

Also, the -cpu and -net options you passed during record are unnecessary, as  those are the defaults.

**Comment by moyix** [comment]
Just adding one extra thing – if you don't remember what options you gave during recording, there's a file named `<recording_name>-rr.cmd` that contains the command line.
