### ISSUE TITLE
Segmentation Fault When Using file_taint

### ISSUE THREAD

**Issue by hst10** [moyix/panda#99]
Hi! 
I am trying file_taint plug-in, but I get some errors. I am not sure whether I am using the flags correctly. 

I used TinyCore Linux, and use the following command to record: 
`~/panda/qemu/x86_64-softmmu/qemu-system-x86_64 ./vdisk.qcow2 -m 1024 -cdrom ~/Downloads/TinyCore-current.iso -vga std -monitor stdio`
I `begin_record tiny` in panda, and I created a file named "foo123.txt" within the TinyCore OS, then `end_record`. 
Then, I use the following command to replay with file_taint plug-in:  
`~/panda/qemu/x86_64-softmmu/qemu-system-x86_64 -replay tiny -m 1024 -vga std -monitor stdio -panda osi  -panda osi_linux:kconf_group=lava32,kconf_file=~/panda/qemu/panda_plugins/osi_linux/kernelinfo.conf  -panda syscalls2:profile=linux_x86 -panda file_taint:filename=foo123.txt,notaint`

(I use lava32 because it is a relatively complete configuration. Missing attributes in the configuration will lead to osi_linux crash)

Then I get the following error message: 
`......`
`Success`
`QEMU 1.0,1 monitor - type 'help' for more information`
`(qemu) loading snapshot`
`... done.`
`opening nondet log for read :   ./tiny-rr-nondet.log`
`Segmentation fault (core dumped)`

Anyone has idea about what's wrong? Thanks!

**Comment by moyix** [comment]
Could you post the full output? The most common cause of a crash with `taint2` is not having enough RAM – the plugin tries to allocate 16x the amount of RAM as you gave the guest OS – so 16GB in the example you gave. It should print out a message if it fails to do so.

As for how to get around it – the simplest thing to do is just give the guest OS less RAM (say, 128MB).

**Comment by hst10** [comment]
The full output is as follows, seems that RAM size is not a problem. Thanks for reminding me the configuration file. I will try create a profile that matches the kernel. 

adding /home/shuang91/panda/qemu/x86_64-softmmu/panda_plugins/panda_osi.so to panda_plugin_files 0
Adding PANDA arg osi_linux:kconf_group=lava32.
Adding PANDA arg osi_linux:kconf_file=/home/shuang91/panda/qemu/panda_plugins/osi_linux/kernelinfo.conf.
adding /home/shuang91/panda/qemu/x86_64-softmmu/panda_plugins/panda_osi_linux.so to panda_plugin_files 1
Adding PANDA arg syscalls2:profile=linux_x86.
adding /home/shuang91/panda/qemu/x86_64-softmmu/panda_plugins/panda_syscalls2.so to panda_plugin_files 2
Adding PANDA arg file_taint:filename=foo123.txt.
Adding PANDA arg file_taint:notaint.
adding /home/shuang91/panda/qemu/x86_64-softmmu/panda_plugins/panda_file_taint.so to panda_plugin_files 3
loading /home/shuang91/panda/qemu/x86_64-softmmu/panda_plugins/panda_osi.so
Success
loading /home/shuang91/panda/qemu/x86_64-softmmu/panda_plugins/panda_osi_linux.so
INFO(osi_linux.cpp:init_plugin): Read kernel info from group "lava32" of file "/home/shuang91/panda/qemu/panda_plugins/osi_linux/kernelinfo.conf".
INFO(osi_linux.cpp:init_plugin): osi_linux initialization complete.
Success
loading /home/shuang91/panda/qemu/x86_64-softmmu/panda_plugins/panda_syscalls2.so
Initializing plugin syscalls2
Success
loading /home/shuang91/panda/qemu/x86_64-softmmu/panda_plugins/panda_file_taint.so
Initializing plugin file_taint
taint_filename = [foo123.txt]
positional_labels = 0
no_taint = 1
end_label = 1000000
first_instr = 0 
panda_require: osi_linux
panda_load_plugin: /home/shuang91/panda/qemu/x86_64-softmmu/panda_plugins/panda_osi_linux.so already loaded
panda_require: osi
panda_load_plugin: /home/shuang91/panda/qemu/x86_64-softmmu/panda_plugins/panda_osi.so already loaded
panda_require: syscalls2
panda_load_plugin: /home/shuang91/panda/qemu/x86_64-softmmu/panda_plugins/panda_syscalls2.so already loaded
Success
QEMU 1.0,1 monitor - type 'help' for more information
(qemu) loading snapshot
... done.
opening nondet log for read :   ./tiny-rr-nondet.log
Segmentation fault (core dumped)
